
- name: apt clean
  shell: apt clean

# - name: apt update
#   shell: apt update

- name: Install MySQL and packages
  apt:
    name: ['mysql-server=5.7.*','python3-mysqldb']
    state: present

# - name: "Upgrade existing packages"
#   apt: 
#     update_cache: yes 
#     upgrade: yes

- name: mysql | copy .my.cnf
  template:
    src:   './templates/.my.cnf'
    dest:  ~/.my.cnf
    mode:  0600

# Remove all anonymous users for all hosts
- name: Remove all anonymous user accounts
  mysql_user:
    name: ""
    state: absent

# Update "root" user password and grant all permissions for all hosts
- name: Update "root" user password and grant all permissions for all hosts
  mysql_user:
    login_user: "{{ db_user }}"
    login_password: "{{db_password}}"
    check_implicit_admin: yes
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "*.*:ALL,GRANT"
    state: present

- name: Create a new database with name "{{db_name}}"
  mysql_db:
    name: "{{db_name}}"
    login_user: "{{db_user}}"
    login_password: "{{db_password}}"
    state: present
  notify: restart mysql


