---
- hosts: all
  become: yes
  remote_user: root

  vars_files:
    - ./vars/common.yml
  pre_tasks: 
    - name: Ensure .ssh directory exists.
      file: 
        dest: "{{ key_file | dirname }}"
        mode: 0700 
        owner: "{{ansible_user}}"
        state: directory

  roles:
  - mysql
  - mattermost
