---
- hosts: all
  become: yes
  remote_user: root
  # vars:
  #   - key_file: "{{ ansible_env.HOME }}/.ssh/web_srv"
  vars_files:
    - ./vars/common.yml
  pre_tasks: 
    - name: Ensure .ssh directory exists.
      file: 
        dest: "{{ key_file | dirname }}"
        mode: 0700 
        owner: "{{ansible_user}}"
        state: directory

    # - name: Add SSH for web-srv
  roles:
  - mysql
  - mattermost
